// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/waraq-rebrand/Current.tsx": () => import("../components/mockups/waraq-rebrand/Current.tsx"),
  "./components/mockups/waraq-rebrand/Orange.tsx": () => import("../components/mockups/waraq-rebrand/Orange.tsx")
};
